In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

1. item , Quantity, price col has nan values to be removed.
2. total Spent	Payment Method	Location nan to either mean / median.

In [44]:
df["Transaction Date"].info()

<class 'pandas.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: Transaction Date
Non-Null Count  Dtype
--------------  -----
9841 non-null   str
dtypes: str(1)
memory usage: 78.3 KB

In [45]:
df.drop_duplicates()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [46]:
df["Item"]= df["Item"].fillna("")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [51]:
for i in list(df.columns):
    df[i]= df[i].fillna("")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,,UNKNOWN,2023-08-30
9996,TXN_9659401,,3,,3.0,Digital Wallet,,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,,2023-03-02
9998,TXN_7695629,Cookie,3,,3.0,Digital Wallet,,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [66]:
df['Total Spent']= df['Total Spent'].replace("ERROR","")
df['Payment Method']=df['Payment Method'].str.replace("UNKNOWN","")
df['Location']=df['Location'].str.replace("UNKNOWN","")

In [60]:
df['Location']= df['Location'].str.replace('[^a-zA-Z0-9]',' ',regex=True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,,UNKNOWN,2023-08-30
9996,TXN_9659401,,3,,3.0,Digital Wallet,,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,,2023-03-02
9998,TXN_7695629,Cookie,3,,3.0,Digital Wallet,,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In store,2023-11-07

In [67]:
df['Transaction Date']=df['Transaction Date'].replace('[^0-9]',"/", regex= True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023/09/08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In store,2023/05/16
2,TXN_4271903,Cookie,4,1.0,,Credit Card,In store,2023/07/19
3,TXN_7034554,Salad,2,5.0,10.0,,,2023/04/27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In store,2023/06/11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,,,2023/08/30
9996,TXN_9659401,,3,,3.0,Digital Wallet,,2023/06/02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,,2023/03/02
9998,TXN_7695629,Cookie,3,,3.0,Digital Wallet,,2023/12/02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In store,2023/11/07

In [80]:
df['Quantity']=df['Quantity'].replace("", df['Quantity'].mean)
df['Price Per Unit']=df['Price Per Unit'].replace("", df['Price Per Unit'].mean)
df['Total Spent']=df['Total Spent'].replace("", df['Total Spent'].mean)

In [85]:
df['Payment Method']=df['Payment Method'].replace("", df['Payment Method'].mean)

In [93]:
for i in df.columns:
    df[i] = df[i].replace("",df[i].mean)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023/09/08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In store,2023/05/16
2,TXN_4271903,Cookie,4,1.0,<bound method Series.mean of 0 4.0\n1 ...,Credit Card,In store,2023/07/19
3,TXN_7034554,Salad,2,5.0,10.0,<bound method Series.mean of 0 Credit...,<bound method Series.mean of 0 Takeaway\...,2023/04/27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In store,2023/06/11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,<bound method Series.mean of 0 Credit...,<bound method Series.mean of 0 Takeaway\...,2023/08/30
9996,TXN_9659401,<bound method Series.mean of 0 Coffee\...,3,<bound method Series.mean of 0 2.0\n1 ...,3.0,Digital Wallet,<bound method Series.mean of 0 Takeaway\...,2023/06/02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,<bound method Series.mean of 0 Takeaway\...,2023/03/02
9998,TXN_7695629,Cookie,3,<bound method Series.mean of 0 2.0\n1 ...,3.0,Digital Wallet,<bound method Series.mean of 0 Takeaway\...,2023/12/02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In store,2023/11/07

In [ ]:
df['Quantity'].mean()

AttributeError: 'list' object has no attribute 'mean'